version: "3.8"

services:
   api-gateway:
    build:
      context: ./api-gateway
    container_name: api_gateway
    depends_on:
      - blog-service
      - stakeholders-service
    ports:
      - "8000:8000"
    environment:
      BLOG_SERVICE_URL: "http://blog-service:8080"
      STAKEHOLDERS_SERVICE_URL: "http://stakeholders-service:8080"
      JWT_SECRET: "your-secret-key-change-in-production"
    networks:
      - tourapp-network

   blog-service:
    build:
      context: ./blog-service
    container_name: blog_service
    restart: always
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MONGO_URI=mongodb://root:pass@mongo:27017/blogdb?authSource=admin
    networks:
      - tourapp-network
    depends_on:
      mongo:
        condition: service_healthy
    

   mongo:
    image: mongo:7
    container_name: blog_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: blogdb
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - tourapp-network

   mongo-express:
    image: mongo-express
    container_name: blog_mongo_express
    restart: always
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - tourapp-network

   follower-service:
    build:
      context: ./follower-service
    container_name: follower_service
    restart: always
    ports:
      - "8083:8083"
    environment:
      PORT: 8083
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: password
    depends_on:
      neo4j:
        condition: service_healthy
    networks:
      - tourapp-network

   neo4j:
    image: neo4j:5
    container_name: follower_neo4j
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
    volumes:
      - neo4j_data:/data
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u neo4j -p password 'RETURN 1'"]
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      - tourapp-network
      

   stakeholders-service:
    build:
      context: ./stakeholders-service
    container_name: stakeholders_service
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/stakeholders_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - tourapp-network

   postgres:
    image: postgres:13-alpine
    container_name: stakeholders_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: stakeholders_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d stakeholders_db"]
      interval: 10s
      timeout: 5s
      retries: 10

    networks:
      - tourapp-network

volumes:
  mongo_data:
  postgres_data:
  neo4j_data:
    


networks:
  tourapp-network:
    driver: bridge
