version: '3.8'

services:
  # Definicija za PostgreSQL bazu
  postgres:
    image: postgres:13-alpine  # Koristimo zvanicnu Postgres sliku
    container_name: blog_db
    environment:
      POSTGRES_USER: postgres      # Korisnicko ime za bazu
      POSTGRES_PASSWORD: root # Sifra za bazu
      POSTGRES_DB: blog_service     # Ime baze koja ce se kreirati
    ports:
      - "5432:5432"  # Mapiramo port sa host masine na kontejner (za pristup spolja)
    volumes:
      - postgres_data:/var/lib/postgresql/data # Cuva podatke baze cak i ako se kontejner obrise

  # Definicija za blog-service
  blog-service:
    build:
      context: ./blog-service  # Putanja do direktorijuma gde je Dockerfile
    container_name: blog_service
    depends_on:
      - postgres  # Govori Docker-u da pokrene 'postgres' servis pre 'blog-service'
    ports:
      - "8080:8080" # Mapiramo port aplikacije
    environment:
      # Prosledjujemo konekcioni string kao environment varijablu
      DB_CONNECTION_STRING: "host=postgres user=postgres password=root dbname=blog_service port=5432"

volumes:
  postgres_data: # Definisemo volume za perzistenciju podataka