version: "3.8"

services:

  postgres:
    image: postgres:13-alpine
    container_name: main_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - tourapp-network

  blog-service:
    build:
      context: ./blog-service
    ports:
      - "8080:8080"
    environment:
      MONGO_URI: mongodb://root:pass@mongo:27017/blogdb?authSource=admin
    depends_on:
      - mongo
    networks:
      - tourapp-network

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    networks:
      - tourapp-network

  stakeholders-service:
    build:
      context: ./stakeholders-service
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/stakeholders_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - postgres
    networks:
      - tourapp-network

  tour-service:
    build:
      context: ./tour-service
    ports:
      - "8082:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=tour_db;Username=postgres;Password=root"
    depends_on:
      - postgres
    networks:
      - tourapp-network

volumes:
  postgres_data:

networks:
  tourapp-network:
    driver: bridge