// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/blog.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmptyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	mi := &file_proto_blog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_proto_blog_proto_rawDescGZIP(), []int{0}
}

type EmptyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyResponse) Reset() {
	*x = EmptyResponse{}
	mi := &file_proto_blog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResponse) ProtoMessage() {}

func (x *EmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResponse.ProtoReflect.Descriptor instead.
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return file_proto_blog_proto_rawDescGZIP(), []int{1}
}

type CreateWelcomeBlogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWelcomeBlogRequest) Reset() {
	*x = CreateWelcomeBlogRequest{}
	mi := &file_proto_blog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWelcomeBlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWelcomeBlogRequest) ProtoMessage() {}

func (x *CreateWelcomeBlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWelcomeBlogRequest.ProtoReflect.Descriptor instead.
func (*CreateWelcomeBlogRequest) Descriptor() ([]byte, []int) {
	return file_proto_blog_proto_rawDescGZIP(), []int{2}
}

func (x *CreateWelcomeBlogRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreateWelcomeBlogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlogId        string                 `protobuf:"bytes,1,opt,name=blogId,proto3" json:"blogId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWelcomeBlogResponse) Reset() {
	*x = CreateWelcomeBlogResponse{}
	mi := &file_proto_blog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWelcomeBlogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWelcomeBlogResponse) ProtoMessage() {}

func (x *CreateWelcomeBlogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWelcomeBlogResponse.ProtoReflect.Descriptor instead.
func (*CreateWelcomeBlogResponse) Descriptor() ([]byte, []int) {
	return file_proto_blog_proto_rawDescGZIP(), []int{3}
}

func (x *CreateWelcomeBlogResponse) GetBlogId() string {
	if x != nil {
		return x.BlogId
	}
	return ""
}

type DeleteBlogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlogId        string                 `protobuf:"bytes,1,opt,name=blogId,proto3" json:"blogId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBlogRequest) Reset() {
	*x = DeleteBlogRequest{}
	mi := &file_proto_blog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBlogRequest) ProtoMessage() {}

func (x *DeleteBlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBlogRequest.ProtoReflect.Descriptor instead.
func (*DeleteBlogRequest) Descriptor() ([]byte, []int) {
	return file_proto_blog_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteBlogRequest) GetBlogId() string {
	if x != nil {
		return x.BlogId
	}
	return ""
}

type BlogIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlogIdRequest) Reset() {
	*x = BlogIdRequest{}
	mi := &file_proto_blog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlogIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlogIdRequest) ProtoMessage() {}

func (x *BlogIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlogIdRequest.ProtoReflect.Descriptor instead.
func (*BlogIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_blog_proto_rawDescGZIP(), []int{5}
}

func (x *BlogIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CommentMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorId      string                 `protobuf:"bytes,2,opt,name=authorId,proto3" json:"authorId,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentMessage) Reset() {
	*x = CommentMessage{}
	mi := &file_proto_blog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentMessage) ProtoMessage() {}

func (x *CommentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentMessage.ProtoReflect.Descriptor instead.
func (*CommentMessage) Descriptor() ([]byte, []int) {
	return file_proto_blog_proto_rawDescGZIP(), []int{6}
}

func (x *CommentMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CommentMessage) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *CommentMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CommentMessage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CommentMessage) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type BlogMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,5,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	AuthorId      string                 `protobuf:"bytes,6,opt,name=authorId,proto3" json:"authorId,omitempty"`
	Likes         []string               `protobuf:"bytes,7,rep,name=likes,proto3" json:"likes,omitempty"`
	Comments      []*CommentMessage      `protobuf:"bytes,8,rep,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlogMessage) Reset() {
	*x = BlogMessage{}
	mi := &file_proto_blog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlogMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlogMessage) ProtoMessage() {}

func (x *BlogMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlogMessage.ProtoReflect.Descriptor instead.
func (*BlogMessage) Descriptor() ([]byte, []int) {
	return file_proto_blog_proto_rawDescGZIP(), []int{7}
}

func (x *BlogMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BlogMessage) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BlogMessage) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BlogMessage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *BlogMessage) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *BlogMessage) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *BlogMessage) GetLikes() []string {
	if x != nil {
		return x.Likes
	}
	return nil
}

func (x *BlogMessage) GetComments() []*CommentMessage {
	if x != nil {
		return x.Comments
	}
	return nil
}

type BlogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blog          *BlogMessage           `protobuf:"bytes,1,opt,name=blog,proto3" json:"blog,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlogResponse) Reset() {
	*x = BlogResponse{}
	mi := &file_proto_blog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlogResponse) ProtoMessage() {}

func (x *BlogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlogResponse.ProtoReflect.Descriptor instead.
func (*BlogResponse) Descriptor() ([]byte, []int) {
	return file_proto_blog_proto_rawDescGZIP(), []int{8}
}

func (x *BlogResponse) GetBlog() *BlogMessage {
	if x != nil {
		return x.Blog
	}
	return nil
}

type BlogListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blogs         []*BlogMessage         `protobuf:"bytes,1,rep,name=blogs,proto3" json:"blogs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlogListResponse) Reset() {
	*x = BlogListResponse{}
	mi := &file_proto_blog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlogListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlogListResponse) ProtoMessage() {}

func (x *BlogListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_blog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlogListResponse.ProtoReflect.Descriptor instead.
func (*BlogListResponse) Descriptor() ([]byte, []int) {
	return file_proto_blog_proto_rawDescGZIP(), []int{9}
}

func (x *BlogListResponse) GetBlogs() []*BlogMessage {
	if x != nil {
		return x.Blogs
	}
	return nil
}

var File_proto_blog_proto protoreflect.FileDescriptor

const file_proto_blog_proto_rawDesc = "" +
	"\n" +
	"\x10proto/blog.proto\x12\x04blog\x1a\x1fgoogle/protobuf/timestamp.proto\"\x0e\n" +
	"\fEmptyRequest\"\x0f\n" +
	"\rEmptyResponse\"2\n" +
	"\x18CreateWelcomeBlogRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\"3\n" +
	"\x19CreateWelcomeBlogResponse\x12\x16\n" +
	"\x06blogId\x18\x01 \x01(\tR\x06blogId\"+\n" +
	"\x11DeleteBlogRequest\x12\x16\n" +
	"\x06blogId\x18\x01 \x01(\tR\x06blogId\"\x1f\n" +
	"\rBlogIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xca\x01\n" +
	"\x0eCommentMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bauthorId\x18\x02 \x01(\tR\bauthorId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x128\n" +
	"\tcreatedAt\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\tupdatedAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x8f\x02\n" +
	"\vBlogMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x128\n" +
	"\tcreatedAt\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1a\n" +
	"\bimageUrl\x18\x05 \x01(\tR\bimageUrl\x12\x1a\n" +
	"\bauthorId\x18\x06 \x01(\tR\bauthorId\x12\x14\n" +
	"\x05likes\x18\a \x03(\tR\x05likes\x120\n" +
	"\bcomments\x18\b \x03(\v2\x14.blog.CommentMessageR\bcomments\"5\n" +
	"\fBlogResponse\x12%\n" +
	"\x04blog\x18\x01 \x01(\v2\x11.blog.BlogMessageR\x04blog\";\n" +
	"\x10BlogListResponse\x12'\n" +
	"\x05blogs\x18\x01 \x03(\v2\x11.blog.BlogMessageR\x05blogs2\x92\x02\n" +
	"\vBlogService\x129\n" +
	"\vGetAllBlogs\x12\x12.blog.EmptyRequest\x1a\x16.blog.BlogListResponse\x126\n" +
	"\vGetBlogById\x12\x13.blog.BlogIdRequest\x1a\x12.blog.BlogResponse\x12T\n" +
	"\x11CreateWelcomeBlog\x12\x1e.blog.CreateWelcomeBlogRequest\x1a\x1f.blog.CreateWelcomeBlogResponse\x12:\n" +
	"\n" +
	"DeleteBlog\x12\x17.blog.DeleteBlogRequest\x1a\x13.blog.EmptyResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_blog_proto_rawDescOnce sync.Once
	file_proto_blog_proto_rawDescData []byte
)

func file_proto_blog_proto_rawDescGZIP() []byte {
	file_proto_blog_proto_rawDescOnce.Do(func() {
		file_proto_blog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_blog_proto_rawDesc), len(file_proto_blog_proto_rawDesc)))
	})
	return file_proto_blog_proto_rawDescData
}

var file_proto_blog_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_blog_proto_goTypes = []any{
	(*EmptyRequest)(nil),              // 0: blog.EmptyRequest
	(*EmptyResponse)(nil),             // 1: blog.EmptyResponse
	(*CreateWelcomeBlogRequest)(nil),  // 2: blog.CreateWelcomeBlogRequest
	(*CreateWelcomeBlogResponse)(nil), // 3: blog.CreateWelcomeBlogResponse
	(*DeleteBlogRequest)(nil),         // 4: blog.DeleteBlogRequest
	(*BlogIdRequest)(nil),             // 5: blog.BlogIdRequest
	(*CommentMessage)(nil),            // 6: blog.CommentMessage
	(*BlogMessage)(nil),               // 7: blog.BlogMessage
	(*BlogResponse)(nil),              // 8: blog.BlogResponse
	(*BlogListResponse)(nil),          // 9: blog.BlogListResponse
	(*timestamppb.Timestamp)(nil),     // 10: google.protobuf.Timestamp
}
var file_proto_blog_proto_depIdxs = []int32{
	10, // 0: blog.CommentMessage.createdAt:type_name -> google.protobuf.Timestamp
	10, // 1: blog.CommentMessage.updatedAt:type_name -> google.protobuf.Timestamp
	10, // 2: blog.BlogMessage.createdAt:type_name -> google.protobuf.Timestamp
	6,  // 3: blog.BlogMessage.comments:type_name -> blog.CommentMessage
	7,  // 4: blog.BlogResponse.blog:type_name -> blog.BlogMessage
	7,  // 5: blog.BlogListResponse.blogs:type_name -> blog.BlogMessage
	0,  // 6: blog.BlogService.GetAllBlogs:input_type -> blog.EmptyRequest
	5,  // 7: blog.BlogService.GetBlogById:input_type -> blog.BlogIdRequest
	2,  // 8: blog.BlogService.CreateWelcomeBlog:input_type -> blog.CreateWelcomeBlogRequest
	4,  // 9: blog.BlogService.DeleteBlog:input_type -> blog.DeleteBlogRequest
	9,  // 10: blog.BlogService.GetAllBlogs:output_type -> blog.BlogListResponse
	8,  // 11: blog.BlogService.GetBlogById:output_type -> blog.BlogResponse
	3,  // 12: blog.BlogService.CreateWelcomeBlog:output_type -> blog.CreateWelcomeBlogResponse
	1,  // 13: blog.BlogService.DeleteBlog:output_type -> blog.EmptyResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_blog_proto_init() }
func file_proto_blog_proto_init() {
	if File_proto_blog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_blog_proto_rawDesc), len(file_proto_blog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_blog_proto_goTypes,
		DependencyIndexes: file_proto_blog_proto_depIdxs,
		MessageInfos:      file_proto_blog_proto_msgTypes,
	}.Build()
	File_proto_blog_proto = out.File
	file_proto_blog_proto_goTypes = nil
	file_proto_blog_proto_depIdxs = nil
}
